"""202606141245

Revision ID: f7674479c4e9
Revises: None
Create Date: 2026-06-14 12:46:09.274548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7674479c4e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_reply_rule',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('account_id', sa.BigInteger(), nullable=False, comment='所属账号 ID'),
    sa.Column('trigger_keyword', sa.String(length=255), nullable=False, comment='触发关键词'),
    sa.Column('reply_content', sa.Text(), nullable=False, comment='自动回复内容'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='规则启用状态'),
    sa.Column('trigger_mode', sa.String(length=20), nullable=False, comment='触发模式: keyword|all'),
    sa.Column('keywords', sa.JSON(), nullable=True, comment='关键词列表(JSON数组)'),
    sa.Column('scope_mode', sa.String(length=20), nullable=False, comment='会话范围: all|specific'),
    sa.Column('conversation_ids', sa.JSON(), nullable=True, comment='指定会话ID列表(JSON数组)'),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=True, comment='归属用户 ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（数据库服务器时间）'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（数据库服务器时间）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auto_reply_rule_account_id'), 'auto_reply_rule', ['account_id'], unique=False)
    op.create_index(op.f('ix_auto_reply_rule_owner_user_id'), 'auto_reply_rule', ['owner_user_id'], unique=False)
    op.create_table('file_record',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('local_path', sa.String(length=512), nullable=False, comment='本地临时文件路径'),
    sa.Column('s3_key', sa.String(length=512), nullable=True, comment='S3 对象 Key'),
    sa.Column('s3_url', sa.String(length=1024), nullable=True, comment='S3 访问 URL'),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False, comment='文件大小（字节）'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='文件生命周期状态'),
    sa.Column('expires_at', sa.DateTime(), nullable=True, comment='文件过期时间'),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=True, comment='归属用户 ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（数据库服务器时间）'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（数据库服务器时间）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_file_record_status_expires', 'file_record', ['status', 'expires_at'], unique=False)
    op.create_index(op.f('ix_file_record_owner_user_id'), 'file_record', ['owner_user_id'], unique=False)
    op.create_table('instance_heartbeat',
    sa.Column('instance_id', sa.String(length=255), nullable=False, comment='实例 ID'),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=False, comment='最后一次心跳时间'),
    sa.PrimaryKeyConstraint('instance_id')
    )
    op.create_table('message_content',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('account_id', sa.BigInteger(), nullable=False, comment='所属账号 ID'),
    sa.Column('content_type', sa.String(length=16), nullable=False, comment='消息内容类型（text/media/emoji）'),
    sa.Column('text_content', sa.Text(), nullable=True, comment='文本内容'),
    sa.Column('media_type', sa.String(length=32), nullable=True, comment='媒体类型（image/video/audio/file/sticker）'),
    sa.Column('media_url', sa.String(length=1024), nullable=True, comment='媒体 URL'),
    sa.Column('media_key', sa.String(length=512), nullable=True, comment='媒体对象 Key'),
    sa.Column('emoji', sa.String(length=64), nullable=True, comment='表情内容'),
    sa.Column('caption', sa.Text(), nullable=True, comment='媒体说明或补充文案'),
    sa.Column('extra_json', sa.Text(), nullable=False, comment='扩展 JSON'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='内容启用状态'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（数据库服务器时间）'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（数据库服务器时间）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_content_account_id'), 'message_content', ['account_id'], unique=False)
    op.create_table('message_content_media',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('message_content_id', sa.BigInteger(), nullable=False, comment='关联消息模板 ID'),
    sa.Column('media_type', sa.String(length=32), nullable=False, comment='媒体类型（image/video/audio/file/sticker）'),
    sa.Column('media_url', sa.String(length=1024), nullable=True, comment='媒体 URL'),
    sa.Column('media_key', sa.String(length=512), nullable=True, comment='媒体对象 Key'),
    sa.Column('caption', sa.Text(), nullable=True, comment='单媒体说明'),
    sa.Column('sort_order', sa.BigInteger(), nullable=False, comment='排序号'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（数据库服务器时间）'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（数据库服务器时间）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_content_media_message_content_id'), 'message_content_media', ['message_content_id'], unique=False)
    op.create_table('proxy_info',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('proxy_host', sa.String(length=255), nullable=False, comment='代理主机地址'),
    sa.Column('proxy_port', sa.Integer(), nullable=False, comment='代理端口'),
    sa.Column('username', sa.String(length=128), nullable=True, comment='代理认证用户名'),
    sa.Column('password', sa.String(length=128), nullable=True, comment='代理认证密码'),
    sa.Column('proxy_type', sa.String(length=50), server_default='socks5', nullable=False, comment='代理协议类型（socks5, socks4, http）'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='代理启用状态'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（数据库服务器时间）'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（数据库服务器时间）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_message_task',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('account_id', sa.BigInteger(), nullable=False, comment='执行账号 ID'),
    sa.Column('message_content_id', sa.BigInteger(), nullable=True, comment='关联消息内容 ID'),
    sa.Column('trigger_type', sa.String(length=64), nullable=False, comment='规则触发类型'),
    sa.Column('condition_json', sa.Text(), nullable=False, comment='触发条件 JSON'),
    sa.Column('action_json', sa.Text(), nullable=False, comment='执行动作 JSON'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='规则启用状态'),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=True, comment='归属用户 ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（数据库服务器时间）'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（数据库服务器时间）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_message_task_account_id'), 'rule_message_task', ['account_id'], unique=False)
    op.create_index(op.f('ix_rule_message_task_is_active'), 'rule_message_task', ['is_active'], unique=False)
    op.create_index(op.f('ix_rule_message_task_owner_user_id'), 'rule_message_task', ['owner_user_id'], unique=False)
    op.create_table('scheduled_message_task',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('account_id', sa.BigInteger(), nullable=False, comment='执行账号 ID'),
    sa.Column('message_content_id', sa.BigInteger(), nullable=True, comment='关联消息内容 ID'),
    sa.Column('cron_expr', sa.String(length=64), nullable=False, comment='Cron 定时表达式'),
    sa.Column('target_identifier', sa.String(length=255), nullable=False, comment='目标会话标识'),
    sa.Column('message_template', sa.Text(), nullable=True, comment='兼容旧版的文本模板'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='任务启用状态'),
    sa.Column('scope_mode', sa.String(length=20), nullable=False, comment='会话范围: all|specific'),
    sa.Column('conversation_ids', sa.JSON(), nullable=True, comment='指定会话ID列表(JSON数组)'),
    sa.Column('message_ids', sa.JSON(), nullable=True, comment='关联消息内容ID列表(JSON数组)'),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=True, comment='归属用户 ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（数据库服务器时间）'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（数据库服务器时间）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_message_task_account_id'), 'scheduled_message_task', ['account_id'], unique=False)
    op.create_index(op.f('ix_scheduled_message_task_is_active'), 'scheduled_message_task', ['is_active'], unique=False)
    op.create_index(op.f('ix_scheduled_message_task_owner_user_id'), 'scheduled_message_task', ['owner_user_id'], unique=False)
    op.create_table('task_execution_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('task_type', sa.String(length=16), nullable=False, comment='任务类型（scheduled/rule）'),
    sa.Column('task_id', sa.BigInteger(), nullable=False, comment='任务 ID'),
    sa.Column('account_id', sa.BigInteger(), nullable=False, comment='执行账号 ID'),
    sa.Column('message_content_id', sa.BigInteger(), nullable=True, comment='关联消息内容 ID'),
    sa.Column('send_log_id', sa.BigInteger(), nullable=True, comment='关联发送日志 ID'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='执行状态（running/success/failed/skipped）'),
    sa.Column('started_at', sa.DateTime(), nullable=False, comment='开始时间'),
    sa.Column('finished_at', sa.DateTime(), nullable=True, comment='结束时间'),
    sa.Column('duration_ms', sa.BigInteger(), nullable=False, comment='执行耗时毫秒'),
    sa.Column('target_identifier', sa.String(length=255), nullable=False, comment='目标会话标识'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('shard_index', sa.BigInteger(), nullable=False, comment='分片索引'),
    sa.Column('total_shards', sa.BigInteger(), nullable=False, comment='分片总数'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（数据库服务器时间）'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（数据库服务器时间）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_execution_log_account_id'), 'task_execution_log', ['account_id'], unique=False)
    op.create_index(op.f('ix_task_execution_log_task_id'), 'task_execution_log', ['task_id'], unique=False)
    op.create_table('telegram_account',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('phone_number', sa.String(length=64), nullable=False, comment='Telegram 账号手机号（唯一）'),
    sa.Column('session_string', sa.String(length=2048), nullable=True, comment='Telethon 会话字符串'),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=True, comment='Telegram 平台用户 ID'),
    sa.Column('display_name', sa.String(length=255), nullable=True, comment='账号展示名称'),
    sa.Column('is_online', sa.Boolean(), nullable=False, comment='账号在线状态'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='账号启用状态'),
    sa.Column('proxy_id', sa.BigInteger(), nullable=True, comment='关联代理 ID'),
    sa.Column('api_id', sa.Integer(), nullable=True, comment='账号自定义 Telegram API ID'),
    sa.Column('api_hash', sa.String(length=255), nullable=True, comment='账号自定义 Telegram API Hash'),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=True, comment='归属用户 ID'),
    sa.Column('claimed_by', sa.String(length=255), nullable=True, comment='当前认领此账号的号池实例 ID'),
    sa.Column('claimed_at', sa.DateTime(), nullable=True, comment='最后一次认领或续租的时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（数据库服务器时间）'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（数据库服务器时间）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_telegram_account_is_active'), 'telegram_account', ['is_active'], unique=False)
    op.create_index(op.f('ix_telegram_account_owner_user_id'), 'telegram_account', ['owner_user_id'], unique=False)
    op.create_table('telegram_message',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('message_content_id', sa.BigInteger(), nullable=True, comment='关联消息内容 ID'),
    sa.Column('source_type', sa.String(length=16), nullable=False, comment='消息来源类型（manual/scheduled/rule/auto_reply）'),
    sa.Column('account_id', sa.BigInteger(), nullable=False, comment='托管账号 ID'),
    sa.Column('conversation_id', sa.BigInteger(), nullable=True, comment='会话 ID'),
    sa.Column('conversation_peer', sa.String(length=255), nullable=False, comment='会话可读标识'),
    sa.Column('grouped_id', sa.BigInteger(), nullable=True, comment='Telegram 消息组 ID（相册/媒体组）'),
    sa.Column('group_index', sa.BigInteger(), nullable=False, comment='同组消息排序'),
    sa.Column('peer_type', sa.String(length=16), nullable=False, comment='会话类型（user/chat/channel/unknown）'),
    sa.Column('peer_id', sa.BigInteger(), nullable=True, comment='会话对象 ID'),
    sa.Column('sender_telegram_user_id', sa.BigInteger(), nullable=True, comment='发送者 Telegram 用户 ID'),
    sa.Column('direction', sa.String(length=16), nullable=False, comment='消息方向（out/in）'),
    sa.Column('content_type', sa.String(length=16), nullable=False, comment='消息内容类型（text/media/emoji）'),
    sa.Column('text_content', sa.Text(), nullable=True, comment='文本内容'),
    sa.Column('media_type', sa.String(length=32), nullable=True, comment='媒体类型'),
    sa.Column('media_url', sa.String(length=1024), nullable=True, comment='媒体 URL'),
    sa.Column('media_key', sa.String(length=512), nullable=True, comment='媒体对象 Key'),
    sa.Column('emoji', sa.String(length=64), nullable=True, comment='表情内容'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='消息状态（pending/sent/failed）'),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True, comment='Telegram 消息 ID'),
    sa.Column('reply_to_telegram_message_id', sa.BigInteger(), nullable=True, comment='回复的 Telegram 消息 ID'),
    sa.Column('forward_from_telegram_user_id', sa.BigInteger(), nullable=True, comment='转发来源 Telegram 用户 ID'),
    sa.Column('source_message_id', sa.BigInteger(), nullable=True, comment='回复/转发来源消息 ID'),
    sa.Column('task_execution_log_id', sa.BigInteger(), nullable=True, comment='关联任务执行日志 ID'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('sent_at', sa.DateTime(), nullable=True, comment='消息发送时间'),
    sa.Column('message_at', sa.DateTime(), nullable=True, comment='消息时间（入站为接收时间，出站为发送时间）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（数据库服务器时间）'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（数据库服务器时间）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'conversation_peer', 'telegram_message_id', name='uq_telegram_message_account_peer_msg_id')
    )
    op.create_index('idx_telegram_message_account_direction_id', 'telegram_message', ['account_id', 'direction', 'id'], unique=False)
    op.create_index('idx_telegram_message_dir_created_status', 'telegram_message', ['direction', 'created_at', 'status'], unique=False)
    op.create_index(op.f('ix_telegram_message_status'), 'telegram_message', ['status'], unique=False)
    op.create_table('telegram_message_media',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=False, comment='关联会话消息 ID'),
    sa.Column('grouped_id', sa.BigInteger(), nullable=True, comment='Telegram 消息组 ID'),
    sa.Column('media_type', sa.String(length=32), nullable=False, comment='媒体类型（image/video/audio/file/sticker）'),
    sa.Column('media_url', sa.String(length=1024), nullable=True, comment='媒体 URL'),
    sa.Column('media_key', sa.String(length=512), nullable=True, comment='媒体对象 Key'),
    sa.Column('caption', sa.Text(), nullable=True, comment='单媒体说明'),
    sa.Column('telegram_media_id', sa.String(length=128), nullable=True, comment='Telegram 媒体 ID'),
    sa.Column('sort_order', sa.BigInteger(), nullable=False, comment='排序号'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（数据库服务器时间）'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（数据库服务器时间）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_message_media_telegram_message_id'), 'telegram_message_media', ['telegram_message_id'], unique=False)
    op.create_table('telegram_message_send_attempt',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=False, comment='关联会话消息 ID'),
    sa.Column('attempt_no', sa.BigInteger(), nullable=False, comment='尝试序号，从 1 开始'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='尝试状态（sending/sent/failed）'),
    sa.Column('telegram_message_id_value', sa.BigInteger(), nullable=True, comment='本次尝试返回的 Telegram 消息 ID'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='本次尝试错误信息'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='尝试开始时间'),
    sa.Column('finished_at', sa.DateTime(), nullable=True, comment='尝试结束时间'),
    sa.Column('duration_ms', sa.BigInteger(), nullable=False, comment='尝试耗时毫秒'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（数据库服务器时间）'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（数据库服务器时间）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_message_send_attempt_telegram_message_id'), 'telegram_message_send_attempt', ['telegram_message_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='用户登录邮箱'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('api_key', sa.String(length=255), nullable=False, comment='API 鉴权 Key'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='用户启用状态'),
    sa.Column('is_admin', sa.Boolean(), nullable=False, comment='是否为管理员'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（数据库服务器时间）'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（数据库服务器时间）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_reply_sample',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键 ID'),
    sa.Column('auto_reply_rule_id', sa.BigInteger(), nullable=False, comment='自动回复规则 ID'),
    sa.Column('reply_content', sa.Text(), nullable=False, comment='用户回复内容样本'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（数据库服务器时间）'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（数据库服务器时间）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reply_message',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（数据库服务器时间）'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（数据库服务器时间）'),
    sa.ForeignKeyConstraint(['rule_id'], ['auto_reply_rule.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reply_message_rule_id'), 'reply_message', ['rule_id'], unique=False)
    op.create_table('reply_message_media',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('reply_message_id', sa.BigInteger(), nullable=False),
    sa.Column('file_record_id', sa.BigInteger(), nullable=True),
    sa.Column('sort_order', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='记录创建时间（数据库服务器时间）'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间（数据库服务器时间）'),
    sa.ForeignKeyConstraint(['file_record_id'], ['file_record.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reply_message_id'], ['reply_message.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reply_message_media_reply_message_id'), 'reply_message_media', ['reply_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reply_message_media_reply_message_id'), table_name='reply_message_media')
    op.drop_table('reply_message_media')
    op.drop_index(op.f('ix_reply_message_rule_id'), table_name='reply_message')
    op.drop_table('reply_message')
    op.drop_table('user_reply_sample')
    op.drop_table('user')
    op.drop_index(op.f('ix_telegram_message_send_attempt_telegram_message_id'), table_name='telegram_message_send_attempt')
    op.drop_table('telegram_message_send_attempt')
    op.drop_index(op.f('ix_telegram_message_media_telegram_message_id'), table_name='telegram_message_media')
    op.drop_table('telegram_message_media')
    op.drop_index(op.f('ix_telegram_message_status'), table_name='telegram_message')
    op.drop_index('idx_telegram_message_dir_created_status', table_name='telegram_message')
    op.drop_index('idx_telegram_message_account_direction_id', table_name='telegram_message')
    op.drop_table('telegram_message')
    op.drop_index(op.f('ix_telegram_account_owner_user_id'), table_name='telegram_account')
    op.drop_index(op.f('ix_telegram_account_is_active'), table_name='telegram_account')
    op.drop_table('telegram_account')
    op.drop_index(op.f('ix_task_execution_log_task_id'), table_name='task_execution_log')
    op.drop_index(op.f('ix_task_execution_log_account_id'), table_name='task_execution_log')
    op.drop_table('task_execution_log')
    op.drop_index(op.f('ix_scheduled_message_task_owner_user_id'), table_name='scheduled_message_task')
    op.drop_index(op.f('ix_scheduled_message_task_is_active'), table_name='scheduled_message_task')
    op.drop_index(op.f('ix_scheduled_message_task_account_id'), table_name='scheduled_message_task')
    op.drop_table('scheduled_message_task')
    op.drop_index(op.f('ix_rule_message_task_owner_user_id'), table_name='rule_message_task')
    op.drop_index(op.f('ix_rule_message_task_is_active'), table_name='rule_message_task')
    op.drop_index(op.f('ix_rule_message_task_account_id'), table_name='rule_message_task')
    op.drop_table('rule_message_task')
    op.drop_table('proxy_info')
    op.drop_index(op.f('ix_message_content_media_message_content_id'), table_name='message_content_media')
    op.drop_table('message_content_media')
    op.drop_index(op.f('ix_message_content_account_id'), table_name='message_content')
    op.drop_table('message_content')
    op.drop_table('instance_heartbeat')
    op.drop_index(op.f('ix_file_record_owner_user_id'), table_name='file_record')
    op.drop_index('idx_file_record_status_expires', table_name='file_record')
    op.drop_table('file_record')
    op.drop_index(op.f('ix_auto_reply_rule_owner_user_id'), table_name='auto_reply_rule')
    op.drop_index(op.f('ix_auto_reply_rule_account_id'), table_name='auto_reply_rule')
    op.drop_table('auto_reply_rule')
    # ### end Alembic commands ###
